services:
  api:
    build: .
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  ui:
    build: .
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: ["streamlit", "run", "app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]
